[tool.poetry]
name = "visionapi"
version = "0.2.0"
description = ""
authors = ["flonix8 <flstanek@googlemail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
protobuf = "^4.23.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
